# Generated by Django 4.0.3 on 2022-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Randeveryday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(default='Do 10 bottle flipsMake a new friend on DiscordDo not use your phone for 2 hours (Excluding sleeping time and attend important calls only)Sleep at 9PM and wake up at 6AM (Your timezone)Drink chilled water after waking upDrink 4 litres of water todayJog 30 mins in the morning and 30 mins in the eveningDo not watch the television for 4 hours and instead read a bookMake paper planes and fly themSolve theseStich out a design on a waste fabricClean up the wardrobeReplace batteries of old remotes of A.Cs, fans, etcPlay an instrumentSing a songWrite a letter to anyone, not by e-mailChange the bedsheet and pillow coversGo to the store room, pick a random item and clean itDelete unnecessary screenshots and go down the memory laneCut your nails (if male). Paint your nails (if female)Walk down a street and find a homeless person and give 5 units of your currency (Eg. $5, ₹5, etc)', max_length=1000)),
            ],
        ),
    ]
