# Generated by Django 4.0.3 on 2022-04-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_randbored'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Randbored',
        ),
        migrations.DeleteModel(
            name='Randeveryday',
        ),
    ]
