# Generated by Django 4.0.3 on 2022-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_delete_randbored_delete_randeveryday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Randbored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('options', models.CharField(default='Solve aptitude problems; Comprehension; Fill in the blanks; Paint a picture; Cook recipies; Excerise; Draw what comes to your mind; ', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Randeveryday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('options', models.CharField(default='Do 10 bottle flips; Make a new friend on Discord; Do not use your phone for 2 hours (Excluding sleeping time and attend important calls only); Sleep at 9PM and wake up at 6AM (Your timezone); Drink chilled water after waking up; Drink 4 litres of water today; Jog 30 mins in the morning and 30 mins in the evening; Do not watch the television for 4 hours and instead read a book; Make paper planes and fly them; Write an essay on "The Sun"; Stich out a design on a waste fabric; Clean up the wardrobe; Replace batteries of old remotes of A.Cs, fans, etc; Play an instrument; Learn the lyrics and sing the song; Write a letter to anyone, not by e-mail; Change the bedsheet and pillow covers; Go to the store room of your house, pick a random item and clean it; Delete unnecessary screenshots and go down the memory lane; Cut your nails (if male). Paint your nails (if female); Walk down a street and find a homeless person and give 5 units of your currency (Eg. $5, ₹5, etc); ', max_length=1000)),
            ],
        ),
    ]
