# Generated by Django 4.0.3 on 2022-04-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Randbored',
        ),
    ]
