# Generated by Django 4.0.3 on 2022-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_randbored'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('asked', models.BooleanField(default=False)),
            ],
        ),
    ]
