# Generated by Django 4.0.3 on 2022-04-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_emailsending'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsending',
            name='username',
            field=models.CharField(default='new_user', max_length=256),
            preserve_default=False,
        ),
    ]
